# Generated by Django 5.0.4 on 2024-05-31 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('available_times', models.CharField(blank=True, max_length=100)),
                ('clinic_address', models.CharField(blank=True, max_length=200)),
                ('profile_completed', models.BooleanField(default=False)),
                ('consultation_fee', models.CharField(blank=True, default=0.0, max_length=10)),
                ('pmdc_number', models.CharField(editable=False, max_length=7, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ManyToManyField(related_name='specializations', to='doctor.specialization')),
            ],
        ),
    ]
